name: Bug Report
description: File a bug report
labels: ["Bug"]
body:
  - type: checkboxes
    id: searched
    attributes:
      label: Terms
      options:
        - label: "I'm using the very latest version of CinematicsStudio and its dependencies."
          required: true
        - label: I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
          required: true
        - label: I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
          required: true
        - label: I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.
          required: true
  - type: input
    id: discord_tag
    attributes:
      label: Discord tag (optional)
      description: How can we get in touch with you if we need more info?
      placeholder: ex. DiscordTag#0001
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: "Example: I can't interact with custom furniture if I'm in my own claim"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the issue
      description: Describe how to reproduce the issue step by step
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: server_version
    attributes:
      label: Server version
      description: "(run `/version` command and paste it here)"
      placeholder: |
        Run `/version` command and paste it here
        
        Example:
        This server is running Paper version git-Paper-788 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)"
  - type: textarea
    id: plugin_version
    attributes:
      label: CinematicsStudio Version
      placeholder: |
        DO NOT WRITE 'LATEST', run command `/version CinematicsStudio` and paste it here.
        
        Example:
        CinematicsStudio version 2.4.17
    validations:
      required: true
  - type: textarea
    id: protocollib_version
    attributes:
      label: ProtocolLib Version
      placeholder: |
        DO NOT WRITE 'LATEST', run command `/version ProtocolLib` and paste it here.
        
        Example:
        ProtocolLib version 2.4.17
    validations:
      required: true
  - type: textarea
    id: lonelibs_version
    attributes:
      label: LoneLibs Version
      placeholder: |
        DO NOT WRITE 'LATEST', run command `/version LoneLibs` and paste it here.
        
        Example:
        LoneLibs version 2.4.17
    validations:
      required: true
  - type: textarea
    id: full_server_log
    attributes:
      label: FULL server log
      placeholder: "You can drag and drop your full server log here"      
  - type: textarea
    id: logs
    attributes:
      label: Error (optional)
      description: Please copy and paste any error you got (this will be automatically formatted into code).
      render: shell
      placeholder: |
        [19:26:04] [Craft Scheduler Thread - 18 - CinematicsStudio/WARN]: [CinematicsStudio] Plugin CinematicsStudio v2.4.16 generated an exception while executing task 22801
          java.lang.ExceptionInInitializerError: null
            at dev.lone.CinematicsStudio.l.j.a(SourceFile:166) ~[CinematicsStudio.jar:?]
            at dev.lone.CinematicsStudio.l.j.av(SourceFile:104) ~[CinematicsStudio.jar:?]
            at dev.lone.CinematicsStudio.l.a.a(SourceFile:164) ~[CinematicsStudio.jar:?]
            at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-84]
            at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Airplane-84]
            at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Airplane-84]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
            at java.lang.Thread.run(Thread.java:831) [?:?]
          Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.util.zip.ZipEntry.size accessible: module java.base does not "opens java.util.zip" to unnamed module @6f6969ca
            at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
            at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
            at java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) ~[?:?]
            at java.lang.reflect.Field.setAccessible(Field.java:171) ~[?:?]
            at com.comphenix.protocol.reflect.FieldUtils.getField(FieldUtils.java:111) ~[PROTOCOLLIB.jar:?]
            at dev.lone.CinematicsStudio.l.k.<clinit>(SourceFile:12) ~[CinematicsStudio.jar:?]
            ... 9 more
  - type: textarea
    id: configuration_plugin
    attributes:
      label: CinematicsStudio config.yml
      description: Please copy and paste the config.yml file of CinematicsStudio (this will be automatically formatted into code).
      render: shell
      placeholder: | 
        metrics: true
        update-checker: true
        disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
        resource-pack:
          hosting:
            no-host:
              enabled: false
            auto-external-host:
              enabled: false
  - type: textarea
    id: configuration_item
    attributes:
      label: Problematic items yml configuration file (optional)
      description: Please copy and paste the file of your item (this will be automatically formatted into code).
      render: shell
      placeholder: | 
        leather_backpack:
          display_name: "Leather Backpack"
          type: BODY_ITEM
          model:
            gui: potion:300001
            normal: potion:300001
            self: potion:300002
          dye:
            enabled: true
            default: "#542900"
  - type: textarea
    id: configuration_files
    attributes:
      label: Other files, you can drag and drop them here to upload. (optional)
      description: Drag and drop your files here.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos (you can drag and drop files or paste links)
      description: If applicable, add screenshots to help explain your problem (you can drag and drop files or paste links).
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report!
